
spring:
  ai:
    mcp:
      server:
        name: image-search-mcp-server  # MCP?????
        version: 0.0.1                 # ??????
        type: SYNC                     # ??????????
        # stdio
        stdio: true                    # ??????????
  # stdio
  main:
    web-application-type: none         # ??Web??????Web???
    banner-mode: off                   # ??Spring Boot????
